name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: 'ubuntu-22.04'

    steps:
      - run: sudo apt-get update && sudo apt-get install wine64
      - run: wine --version
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: GOOS=windows go test -c . -o runtest.exe
        working-directory: ./ecr-login
      - run: wine ./runtest.exe
        working-directory: ./ecr-login
